import React,{useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {projectStudies} from '../content/project-studies';
import ProjectIllustration from './ProjectIllustration';
import '../styles/study.css';
import '../styles/diagram.css';
import '../styles/project-studies.css';
gsap.registerPlugin(ScrollTrigger);
function Rules(){return <div className="paper-rules"><i/><i/><i/></div>}
function FormSheet({filled=false,title='HWPX 문서'}){return <div className="template-paper"><span className="visual-caption">{title}</span><Rules/><div className="form-table">{['항목','입력 위치','확인 값','비고'].map((s,i)=><div key={s}><span>{s}</span><span className={i===1?'field-focus':''}>{filled&&i===1?'확인한 값':''}</span></div>)}</div><Rules/></div>}
function Board({title,items}){return <div className="review-board"><span className="visual-caption">{title}</span>{items.map((t,i)=><div className="review-row" key={t}><span className="review-index">0{i+1}</span><span>{t}</span></div>)}</div>}
function Detail({type}){
 switch(type){
 case 'hwpx-fields':return <div className="domain-composition paired"><FormSheet/><div className="field-map"><span className="visual-caption">구조와 위치</span>{['문단','표','셀','필드'].map((s,i)=><div key={s} style={{marginLeft:i*16}} className="mapping-item">{s}<Rules/></div>)}</div></div>;
 case 'hwpx-plan':return <div className="domain-composition"><div className="plan-document"><span className="visual-caption">Edit Plan</span><h3>수정할 위치와 값</h3><Board title="확인할 내용" items={['대상 필드','입력값','변경 범위']}/><div className="approval-receipt"><span>승인</span><strong>적용 전 확인</strong></div></div><p className="domain-note">원본 문서와 수정본을 분리하는 흐름</p></div>;
 case 'hwpx-compare':return <div className="domain-composition paired"><FormSheet title="원본"/><FormSheet title="수정본 · 예시" filled/><div className="comparison-caption">구조 변화 · 배치 · 텍스트 넘침 확인</div></div>;
 case 'ownhands-events':return <div className="domain-composition paired"><div className="code-window"><span className="visual-caption">작업의 변화</span><div className="code-line">− 이전 상태</div><Rules/><div className="code-line">+ 변경 사항</div><Rules/></div><Board title="남겨진 기록" items={['Event','Evidence','Review artifact']}/></div>;
 case 'ownhands-evidence':return <div className="domain-composition evidence-file"><div className="evidence-file-header">Evidence</div>{[['ID','근거 식별자'],['hash','무결성 확인 값'],['scope','확인한 범위'],['판정','근거에 따른 결과']].map(([a,b])=><div className="evidence-file-row" key={a}><strong>{a}</strong><span>{b}</span></div>)}<div className="domain-note">Raw Evidence와 검토용 산출물의 구분</div></div>;
 case 'ownhands-decision':return <div className="domain-composition human-review"><div className="review-toolbar">Human review <span>UI 구성안</span></div><Board title="판단 전에 읽을 내용" items={['변경 사항','확인한 근거','남은 불확실성']}/><div className="decision-draft"><span>판단 기록</span><Rules/></div></div>;
 case 'gateway-providers':return <div className="domain-composition provider-composition"><div className="gateway-service"><span className="visual-caption">LLM Gateway</span><h3>서비스의 연결 지점</h3><Rules/></div><div className="provider-stack">{['OpenAI','Anthropic · Google','Ollama'].map(t=><div className="provider-module" key={t}>{t}<span>Provider</span></div>)}</div></div>;
 case 'gateway-runtime':return <div className="domain-composition paired runtime-pair"><div className="runtime-card"><span className="visual-caption">이전 구성 · 현재 비활성</span><h3>SageMaker</h3><div className="cloud-outline">Cloud</div></div><div className="runtime-card"><span className="visual-caption">현재 README 구성</span><h3>Ollama</h3><div className="server-stack">{[1,2,3].map(i=><div key={i}><i/><span/></div>)}</div></div><p className="comparison-caption">환경 전환의 시점·제약·판단 근거를 채울 자리</p></div>;
 default:return <div className="domain-composition retro-composition"><span className="visual-caption">재설계 구상 · 현재 구현 아님</span><div className="protocol-row"><strong>REST</strong><span>요청 전달</span><div className="request-packet">Request</div></div><div className="protocol-row"><strong>SSE</strong><span>응답 스트림</span><div className="stream-packets">{[1,2,3,4].map(i=><i key={i}/>)}</div></div><div className="domain-note">현재 문서의 WebSocket / STOMP와 분리해서 읽기</div></div>
 }
}
export default function ProjectStudy({slug}){
 const p=projectStudies[slug],root=useRef(null);
 useEffect(()=>{document.title=p.name+' | 박태정';const html=document.documentElement;html.classList.add('fowoco-reading');const header=document.querySelector('.site-header');const measure=()=>html.style.setProperty('--study-header-height',`${header?.getBoundingClientRect().height||98}px`);measure();const observer=new ResizeObserver(measure);if(header)observer.observe(header);const media=gsap.matchMedia();media.add('(prefers-reduced-motion: no-preference) and (min-width:901px)',()=>{const ctx=gsap.context(()=>{gsap.utils.toArray('.detail-scene').forEach(scene=>gsap.fromTo(scene.querySelector('.scene-object'),{y:90,scale:.94},{y:0,scale:1,ease:'power2.out',scrollTrigger:{trigger:scene,start:'top 85%',end:'top 10%',scrub:.45}}))},root);return()=>ctx.revert()});return()=>{document.title='박태정 | AI Agent / LLM Application Developer';media.revert();observer.disconnect();html.classList.remove('fowoco-reading');html.style.removeProperty('--study-header-height')}},[slug,p.name]);
 return <div ref={root} className="study project-study"><section className="study-scene overview-scene"><div className="scene-inner"><div className="study-nav"><Link to="/#projects">← 주요 프로젝트</Link></div><header className="overview-heading"><div><p className="study-label">{p.name} · Narrative Skeleton</p><h1>{p.headline[0]}<br/><span>{p.headline[1]}</span></h1></div><p className="study-intro">{p.intro}</p></header><figure className="study-diagram fowoco-overview"><ProjectIllustration project={p}/></figure></div></section>
 {p.scenes.map((s,i)=><section className="study-scene detail-scene" key={s.visual}><div className="scene-inner detail-inner"><header><p className="study-label">0{i+1} / {s.state}</p><h2>{s.title[0]}<br/><span>{s.title[1]}</span></h2><p className="study-intro">{s.text}</p><a className="source-link" href={p.source} target="_blank" rel="noreferrer">기준 문서 ↗</a></header><div className="scene-object"><Detail type={s.visual}/><p className="visual-foot">{s.caption}</p></div></div></section>)}
 <section className="study-scene detail-scene" id="evidence"><div className="scene-inner detail-inner"><header><p className="study-label">04 / Evidence · 확인 범위</p><h2>설명할 내용과,<br/><span>증명할 근거를<br/>구분합니다.</span></h2><p className="study-intro">{p.note}</p><a className="source-link" href={p.source} target="_blank" rel="noreferrer">기준 README ↗</a></header><div className="scene-object"><div className="evidence-boundary"><span>구성안</span><b>≠</b><span>검증 완료</span></div><div className="scope-list">{p.evidence.map(([t,d])=><article className="scope-item" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><p className="visual-foot">저장소 접근 권한이 필요할 수 있습니다. 실제 실행 결과와 성능 수치는 미반영입니다.</p></div></div><footer className="study-footer"><Link to="/">박태정</Link><a href="/documents/taejung-resume.pdf" download>이력서 다운로드 ↗</a></footer></section></div>
}
