import React,{useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {projectStudies} from '../content/project-studies';
import ProjectIllustration from './ProjectIllustration';
import '../styles/study.css';
import '../styles/diagram.css';
import '../styles/project-studies.css';
gsap.registerPlugin(ScrollTrigger);
function Rules(){return <div className="paper-rules"><i/><i/><i/></div>}
function FormSheet({filled=false,title='HWPX 문서'}){return <div className="template-paper"><span className="visual-caption">{title}</span><Rules/><div className="form-table">{['항목','입력 위치','확인 값','비고'].map((s,i)=><div key={s}><span>{s}</span><span className={i===1?'field-focus':''}>{filled&&i===1?'확인한 값':''}</span></div>)}</div><Rules/></div>}
function Board({title,items}){return <div className="review-board"><span className="visual-caption">{title}</span>{items.map((t,i)=><div className="review-row" key={t}><span className="review-index">0{i+1}</span><span>{t}</span></div>)}</div>}
function Detail({type,p_naming=[],p_lifecycle=[],p_criteria=[]}){
 switch(type){
 case 'hwpx-origin':return <div className="origin-composition"><ol className="origin-steps">{[['FOWOCO 안의 문서 처리','app/agents 안에서 문서를 다루던 코드'],['독립 MCP','src/hwp_mcp · 결정적 실행 도구 21종'],['Agent Skills','skills/ · 작업 절차와 판단 기준 5종']].map(([t,d],i)=><li key={t}><span className="origin-index">0{i+1}</span><div><strong>{t}</strong><span>{d}</span></div></li>)}</ol></div>;
 case 'hwpx-interview':return <div className="domain-composition"><div className="disposition-list">{[['provided','값을 확인해 입력'],['intentionally_blank','사용자가 일부러 비움'],['not_applicable','해당 없음'],['manual_after_export','내보낸 뒤 손으로 작성'],['future_e_signature','추후 전자서명']].map(([k,d])=><div className="disposition-row" key={k}><code>{k}</code><span>{d}</span></div>)}</div></div>;
 case 'hwpx-fields':return <div className="domain-composition paired"><FormSheet/><div className="field-map"><span className="visual-caption">구조와 위치</span>{['문단','표','셀','필드'].map((s,i)=><div key={s} style={{marginLeft:i*16}} className="mapping-item">{s}<Rules/></div>)}</div></div>;
 case 'hwpx-plan':return <div className="domain-composition"><div className="plan-document"><span className="visual-caption">Edit Plan</span><h3>수정할 위치와 값</h3><Board title="확인할 내용" items={['대상 필드','입력값','변경 범위']}/><div className="approval-receipt"><span>승인</span><strong>적용 전 확인</strong></div></div><p className="domain-note">원본 문서와 수정본을 분리하는 흐름</p></div>;
 case 'hwpx-compare':return <div className="domain-composition paired"><FormSheet title="원본"/><FormSheet title="수정본 · 예시" filled/><div className="comparison-caption">구조 변화 · 배치 · 텍스트 넘침 확인</div></div>;
 case 'ownhands-naming':return <div className="domain-composition"><div className="naming-table">{p_naming.map(([k,v])=><div className="naming-row" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></div>;
 case 'ownhands-lifecycle':return <div className="lifecycle-composition"><ol className="lifecycle-steps">{p_lifecycle.map((t,i)=><li key={t}><span className="lifecycle-index">0{i+1}</span><strong>{t}</strong></li>)}</ol></div>;
 case 'ownhands-events':return <div className="domain-composition paired"><div className="code-window"><span className="visual-caption">작업의 변화</span><div className="code-line">− 이전 상태</div><Rules/><div className="code-line">+ 변경 사항</div><Rules/></div><Board title="남겨진 기록" items={['Event','Evidence','Review artifact']}/></div>;
 case 'ownhands-evidence':return <div className="domain-composition evidence-file"><div className="evidence-file-header">Evidence</div>{[['ID','근거 식별자'],['hash','무결성 확인 값'],['scope','확인한 범위'],['판정','근거에 따른 결과']].map(([a,b])=><div className="evidence-file-row" key={a}><strong>{a}</strong><span>{b}</span></div>)}<div className="domain-note">Raw Evidence와 검토용 산출물의 구분</div></div>;
 case 'ownhands-decision':return <div className="domain-composition human-review"><div className="review-toolbar">Human review <span>UI 구성안</span></div><Board title="판단 전에 읽을 내용" items={['변경 사항','확인한 근거','남은 불확실성']}/><div className="decision-draft"><span>판단 기록</span><Rules/></div></div>;
 case 'gateway-threshold':return <div className="domain-composition"><div className="threshold-gate"><span className="visual-caption">모든 조건을 통과해야 후보</span><div className="threshold-rows">{['비용 이하','속도 이상','지연 이하','Context Length 이상'].map(t=><div className="threshold-row" key={t}><span>{t}</span><b>AND</b></div>)}</div><p className="threshold-fallback">하나라도 불일치 → 제외 · 남는 후보 없음 → 경고 후 기본 모델</p></div></div>;
 case 'gateway-scoring':return <div className="domain-composition"><div className="criteria-table">{p_criteria.map(([name,unit,dir])=><div className="criteria-row" key={name}><strong>{name}</strong><code>{unit}</code><span>{dir}</span></div>)}</div><p className="domain-note">각 값을 카탈로그 전체의 최소·최대로 0~1 환산</p></div>;
 case 'gateway-weights':return <div className="domain-composition"><div className="weights-formula"><span className="visual-caption">점수 계산</span><p className="formula-line">score = <em>w</em><sub>속도</sub>·n<sub>속도</sub> + <em>w</em><sub>성능</sub>·n<sub>성능</sub> + <em>w</em><sub>비용</sub>·n<sub>비용</sub> + <em>w</em><sub>길이</sub>·n<sub>길이</sub></p><p className="formula-note">가장 높은 점수의 모델을 선택 · 절대 기준 통과 여부가 아닌 상대 평가</p></div></div>;
 case 'gateway-protocol':return <div className="domain-composition retro-composition"><span className="visual-caption">재설계 관점 · 현재 구현 아님</span><div className="protocol-row"><strong>REST</strong><span>요청 전달</span><div className="request-packet">Request</div></div><div className="protocol-row"><strong>SSE</strong><span>응답 스트림</span><div className="stream-packets">{[1,2,3,4].map(i=><i key={i}/>)}</div></div><div className="domain-note">당시 구현한 WebSocket과 분리해서 읽어주세요</div></div>;
 case 'gateway-providers':return <div className="domain-composition provider-composition"><div className="gateway-service"><span className="visual-caption">LLM Gateway</span><h3>서비스의 연결 지점</h3><Rules/></div><div className="provider-stack">{['OpenAI','Anthropic · Google','Ollama'].map(t=><div className="provider-module" key={t}>{t}<span>Provider</span></div>)}</div></div>;
 case 'gateway-runtime':return <div className="domain-composition paired runtime-pair"><div className="runtime-card"><span className="visual-caption">이전 구성 · 현재 비활성</span><h3>SageMaker</h3><div className="cloud-outline">Cloud</div></div><div className="runtime-card"><span className="visual-caption">현재 README 구성</span><h3>Ollama</h3><div className="server-stack">{[1,2,3].map(i=><div key={i}><i/><span/></div>)}</div></div><p className="comparison-caption">환경 전환의 시점·제약·판단 근거를 채울 자리</p></div>;
 default:return <div className="domain-composition retro-composition"><span className="visual-caption">재설계 구상 · 현재 구현 아님</span><div className="protocol-row"><strong>REST</strong><span>요청 전달</span><div className="request-packet">Request</div></div><div className="protocol-row"><strong>SSE</strong><span>응답 스트림</span><div className="stream-packets">{[1,2,3,4].map(i=><i key={i}/>)}</div></div><div className="domain-note">현재 문서의 WebSocket / STOMP와 분리해서 읽기</div></div>
 }
}
export default function ProjectStudy({slug}){
 const p=projectStudies[slug],root=useRef(null);
 useEffect(()=>{document.title=p.name+' | 박태정';const html=document.documentElement;html.classList.add('fowoco-reading');const header=document.querySelector('.site-header');const measure=()=>html.style.setProperty('--study-header-height',`${header?.getBoundingClientRect().height||98}px`);measure();const observer=new ResizeObserver(measure);if(header)observer.observe(header);const media=gsap.matchMedia();media.add('(prefers-reduced-motion: no-preference) and (min-width:901px)',()=>{const ctx=gsap.context(()=>{gsap.utils.toArray('.detail-scene').forEach(scene=>gsap.fromTo(scene.querySelector('.scene-object'),{y:90,scale:.94},{y:0,scale:1,ease:'power2.out',scrollTrigger:{trigger:scene,start:'top 85%',end:'top 10%',scrub:.45}}))},root);return()=>ctx.revert()});return()=>{document.title='박태정 | AI Agent / LLM Application Developer';media.revert();observer.disconnect();html.classList.remove('fowoco-reading');html.style.removeProperty('--study-header-height')}},[slug,p.name]);
 return <div ref={root} className="study project-study"><section className="study-scene overview-scene"><div className="scene-inner"><div className="study-nav"><Link to="/#projects">← 주요 프로젝트</Link></div>{p.purpose?<><header className="overview-heading"><div className="overview-identity"><h1>{p.name}</h1><p className="overview-purpose">{p.purpose}</p></div><dl className="overview-facts"><div><dt>내 역할</dt><dd><span className="overview-team">{p.role.team}</span><ul>{p.role.items.map(t=><li key={t}>{t}</li>)}</ul></dd></div><div><dt>핵심 판단</dt><dd><ul>{p.judgements.map(t=><li key={t}>{t}</li>)}</ul></dd></div></dl></header><nav className="overview-toc" aria-label="이 페이지의 구획">{p.toc.map(t=><a href={t.href} key={t.href}>{t.label}</a>)}</nav></>:<header className="overview-heading"><div><p className="study-label">{p.name}</p><h1>{p.headline[0]}<br/><span>{p.headline[1]}</span></h1></div><p className="study-intro">{p.intro}</p></header>}<figure className="study-diagram fowoco-overview"><ProjectIllustration project={p}/></figure></div></section>
 {p.scenes.map((s,i)=><section className="study-scene detail-scene" id={s.id} key={s.visual}><div className="scene-inner detail-inner"><header><p className="study-label">0{i+1} / {s.state}</p><h2>{s.title[0]}<br/><span>{s.title[1]}</span></h2><p className="study-intro">{s.text}</p><a className="source-link" href={p.source} target="_blank" rel="noreferrer">기준 문서 ↗</a></header><div className="scene-object"><Detail type={s.visual} p_naming={p.naming} p_lifecycle={p.lifecycleSteps} p_criteria={p.criteria}/><p className="visual-foot">{s.caption}</p></div></div></section>)}
 {p.boundary&&<section className="study-scene detail-scene boundary-scene"><div className="scene-inner detail-inner"><header><p className="study-label">{p.boundary.label}</p><h2>실행하는 쪽과,<br/><span>절차를 안내하는 쪽.</span></h2></header><div className="boundary-composition scene-object"><div className="boundary-sides">{p.boundary.sides.map(side=><article className="boundary-side" key={side.owner}><h3>{side.owner}</h3><code className="boundary-path">{side.where}</code><ul>{side.items.map(t=><li key={t}>{t}</li>)}</ul></article>)}</div></div></div></section>}
 <section className="study-scene evidence-scene" id="evidence"><div className="scene-inner detail-inner"><header><p className="study-label">Evidence · 확인 범위</p><h2>설명할 내용과,<br/><span>증명할 근거를<br/>구분합니다.</span></h2><p className="study-intro">{p.note}</p><a className="source-link" href={p.source} target="_blank" rel="noreferrer">기준 README ↗</a>{p.retrospective&&<aside className="retrospective"><h3>{p.retrospective.title}</h3><p>{p.retrospective.text}</p></aside>}</header><div className="evidence-composition"><div className="evidence-boundary"><span>구성안</span><b>≠</b><span>검증 완료</span></div><div className="scope-list">{p.evidence.map(([t,d])=><article className="scope-item" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><p className="visual-foot">저장소는 현재 비공개입니다. 실제 실행 결과와 성능 수치는 미반영입니다.</p></div></div><footer className="study-footer">{p.next&&<Link className="study-next-link" to={p.next.href}>다음 프로젝트 · {p.next.label} <span aria-hidden="true">→</span></Link>}<div className="study-footer-utils"><Link to="/#projects">← 주요 프로젝트</Link><a href="/documents/taejung-resume.pdf" download>이력서 다운로드 <span aria-hidden="true">↗</span></a></div></footer></section></div>
}
